# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "The ParkBoard"
description              : "Descriptions of what I've learned over time."
favicon                  : "/assets/images/banner.png"
avatar                   : "/assets/images/banner.png"
url                      : "https://pjy010218.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog" leave blank if no subpath

publish_mode: editorial_workflow # required for Netlify
future: true # if the post's date is in the future

# Site Author
author:
  name                   : "박준영 Junyoung Park" # appears in the footer and atom feed

comments                 : true # set it to false to disable comments
disqus:
  shortname              : Discussion

atom_feed:
  path                   : # blank (default) uses feed.xml

og_image                 : "/assets/images/mighil.png" # Open Graph/Twitter default site image, optional for seo and social sharing

# Social sharing
# twitter:
  # username               : verfasor # optional, for social sharing

# Analytics
# analytics:
  # google:
    # tracking_id          : UA-128372009-1 # add your google tracking id here

# Reading Files
include:
  - _pages
  - "_redirects"
# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
  papers:
    output: true
    permalink: /papers/:name/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-feed


# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # _papers
  - scope:
      path: ""
      type: papers  # 컬렉션 이름을 'papers'로 지정
    values:
      layout: post   # 'post' 레이아웃 적용 (또는 'page'도 가능)
      comments: true # 일지에도 댓글 허용 시
      share: true    # 일지에도 공유 버튼 표시 시
      
  # _exclude    
exclude:
         - vendor
         - Gemfile
         - Gemfile.lock
         - node_modules
         - gulpfile.js
         - package.json      
